<?php

declare(strict_types=1);
require __DIR__ . '/lib.php';

$config=loadConfig();$query=stringParam('cid');$minSamples=intParam('min_samples',10,0,100);$minReviews=intParam('min_reviews',10,0,100000);$minRating=floatParam('min_rating',4.5,0,5);$assetType=stringParam('asset_type',stringParam('category','all'));$genreId=stringParam('genre_id');
$assetTypes=assetTypeDefinitions();if(!isset($assetTypes[$assetType]))$assetType='all';
$floor=[];$floorError='';try{$floor=resolveDoujinFloor($config);}catch(Throwable $e){$floorError=$e->getMessage();}
$genres=[];$genreError='';if($floor!==[]){try{$genres=fetchGenres($config,(string)$floor['floor_id']);if(!genreExists($genres,$genreId))$genreId='';}catch(Throwable $e){$genreError=$e->getMessage();}}
$catalog=['items'=>[],'scanned'=>0,'api_total'=>0,'stats'=>initialScanStats(),'effective_min_samples'=>max(1,$minSamples)];$catalogError='';if($floor!==[]){try{$catalog=fetchCatalog($config,$floor,$minSamples,$minReviews,$minRating,$assetType,$genreId);}catch(Throwable $e){$catalogError=$e->getMessage();}}
$feedItems=$catalog['items'];$queryError='';if($query!==''&&$floor!==[]){try{$row=feedRowFromItem(fetchItem(normalizeCid($query),$config,$floor));if($row['images']===[])throw new RuntimeException('指定した作品には sampleImageURL.sample_l.image がありません。');$feedItems=array_values(array_filter($feedItems,static function(array $r)use($row):bool{return$r['cid']!==$row['cid'];}));array_unshift($feedItems,$row);}catch(Throwable $e){$queryError=$e->getMessage();}}
$activeGenreName=selectedGenreName($genres,$genreId);$activeConditionText=$assetTypes[$assetType]['label'].' · '.($activeGenreName!==''?$activeGenreName:'全ジャンル');$primaryError=$floorError!==''?$floorError:$catalogError;$stats=$catalog['stats'];
?>
<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#090909"><title>FANZA同人 Swipe Preview</title><link rel="stylesheet" href="assets/app.css"></head><body>
<header class="app-header"><div class="brand"><div class="brand-mark">F</div><div class="brand-copy"><div class="brand-title">Swipe Preview</div><div class="brand-condition"><?=h($activeConditionText)?></div></div></div><div class="header-actions"><div class="feed-count"><span id="activeWork"><?=count($feedItems)>0?'1':'0'?></span> / <?=count($feedItems)?></div><button class="icon-btn" id="filterOpen" type="button"><svg viewBox="0 0 24 24"><path d="M4 6h16M7 12h10M10 18h4"/></svg>絞り込み</button></div></header>
<?php if($queryError!==''):?><div class="error-banner">CID取得エラー: <?=h($queryError)?></div><?php endif;?>
<main class="feed" id="feed" aria-label="作品フィード">
<?php if($primaryError!==''||$feedItems===[]):?><section class="empty-state"><div class="empty-card"><h2><?=$primaryError!==''?'API取得に失敗しました':'条件に合う表示可能作品がありません'?></h2><p><?=h($primaryError!==''?$primaryError:'右上の「絞り込み」を開くと、API走査結果のsample_l枚数分布を確認できます。')?></p><button class="btn btn-primary" type="button" id="emptyFilterOpen">API診断を見る</button></div></section><?php else:?>
<?php foreach($feedItems as $wi=>$row):?><article class="feed-item" data-work-index="<?=$wi?>" data-cid="<?=h($row['cid'])?>" data-title="<?=h($row['title'])?>" data-url="<?=h($row['affiliate_url'])?>"><div class="preview-track" data-preview-track tabindex="0"><?php foreach($row['images'] as $pi=>$url):?><div class="preview-page"><img src="<?=h($url)?>" alt="<?=h($row['title'])?> サンプル <?=$pi+1?>" <?=($wi<2&&$pi<2)?'loading="eager"':'loading="lazy"'?> decoding="async"></div><?php endforeach;?></div><div class="page-counter"><span data-current-page>1</span>&nbsp;/&nbsp;<?=count($row['images'])?></div><div class="load-status" data-load-status>API <?=count($row['images'])?>P · 読込 0/<?=count($row['images'])?></div><?php if(count($row['images'])>1):?><div class="swipe-hint">← 横にスワイプして読む →</div><?php endif;?><div class="item-gradient"></div><div class="item-info"><div class="item-type"><?=h($row['asset_label'])?> · API素材 <?=h($row['asset_bucket'])?></div><h2 class="item-title"><?=h($row['title']?:$row['cid'])?></h2><div class="item-stats"><span class="stat-chip">★ <strong><?=h(number_format((float)$row['rating'],1,'.',''))?></strong></span><span class="stat-chip">レビュー <strong><?=(int)$row['reviews']?></strong></span><span class="stat-chip">サンプル <strong><?=count($row['images'])?></strong>P</span><?php if($row['price']!==''):?><span class="stat-chip"><strong><?=h($row['price'])?></strong></span><?php endif;?></div><?php if($row['genres']):?><div class="genre-line"><?=h(implode(' / ',array_slice($row['genres'],0,6)))?></div><?php endif;?><?php if(filter_var($row['affiliate_url'],FILTER_VALIDATE_URL)):?><a class="open-link" href="<?=h($row['affiliate_url'])?>" target="_blank" rel="noopener noreferrer">FANZAで続きを読む <svg viewBox="0 0 24 24"><path d="M7 17 17 7M9 7h8v8"/></svg></a><?php endif;?></div><div class="action-rail"><button class="action-btn" type="button" data-like><span class="action-icon"><svg viewBox="0 0 24 24"><path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.6l-1-1a5.5 5.5 0 0 0-7.8 7.8l1 1L12 21l7.8-7.6 1-1a5.5 5.5 0 0 0 0-7.8Z"/></svg></span><span class="action-label">いいね</span></button><button class="action-btn" type="button" data-save><span class="action-icon"><svg viewBox="0 0 24 24"><path d="M6 4h12v17l-6-4-6 4V4Z"/></svg></span><span class="action-label">保存</span></button><button class="action-btn" type="button" data-share><span class="action-icon"><svg viewBox="0 0 24 24"><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m8.6 10.5 6.8-4M8.6 13.5l6.8 4"/></svg></span><span class="action-label">共有</span></button></div><?php if($wi<count($feedItems)-1):?><div class="next-hint">SWIPE UP</div><?php endif;?></article><?php endforeach;?><?php endif;?></main>
<div class="sheet-backdrop" id="sheetBackdrop"></div><aside class="sheet" id="filterSheet" aria-hidden="true"><div class="sheet-handle"></div><div class="sheet-head"><div class="sheet-title">作品を絞り込む / API診断</div><button class="close-btn" id="filterClose" type="button">×</button></div><div class="api-note"><strong>重要:</strong> ItemListの <code>iteminfo.genre</code> はジャンルタグで、作品形式ではありません。このツールではAPIが返す <code>imageURL / sampleImageURL</code> の <code>/digital/comic|cg|game|voice/</code> を「API素材タイプ」として別軸で判定します。</div>
<form method="get" id="filterForm"><div class="filters"><div class="field"><label for="asset_type">API素材タイプ</label><select id="asset_type" name="asset_type"><?php foreach($assetTypes as $key=>$def):?><option value="<?=h($key)?>" <?=$assetType===$key?'selected':''?>><?=h($def['label'])?></option><?php endforeach;?></select></div><div class="field"><label for="genre_id">ジャンル</label><select id="genre_id" name="genre_id"><option value="">すべて</option><?php foreach($genres as $g):?><option value="<?=h((string)$g['id'])?>" <?=$genreId===(string)$g['id']?'selected':''?>><?=h((string)$g['name'])?></option><?php endforeach;?></select><?php if($genreError!==''):?><div class="genre-note">GenreSearch: <?=h($genreError)?></div><?php endif;?></div><div class="field"><label for="min_samples">最低sample_l枚数</label><input id="min_samples" type="number" name="min_samples" min="0" max="100" value="<?=$minSamples?>"></div><div class="field"><label for="min_reviews">最低レビュー件数</label><input id="min_reviews" type="number" name="min_reviews" min="0" max="100000" value="<?=$minReviews?>"></div><div class="field field--full"><label for="min_rating">最低平均評価</label><input id="min_rating" type="number" name="min_rating" min="0" max="5" step="0.1" value="<?=h(number_format($minRating,1,'.',''))?>"></div></div>
<div class="filter-summary"><?php if($floor!==[]):?>API: <?=h($floor['site_code'])?> / <?=h($floor['service_code'])?> / <?=h($floor['floor_code'])?> / floor_id <?=h($floor['floor_id'])?><br><?php endif;?>現在: <?=h($activeConditionText)?> / sample_l <?=$minSamples?>枚以上 / レビュー <?=$minReviews?>件以上 / 評価 <?=h(number_format($minRating,1,'.',''))?>以上<br>走査: <?=(int)$catalog['scanned']?>件<?=$catalog['api_total']>0?' / API該当総数 '.(int)$catalog['api_total'].'件':''?> / フィード: <?=count($feedItems)?>作品<?php if($minSamples<1):?><br>※フィード表示には画像が必要なため、sample_l=0件は診断には含めますが表示対象外です。<?php endif;?></div>
<div class="diag"><div class="diag-title">sample_l 枚数分布</div><div class="diag-sub">現在のジャンル条件で取得した最大800件を、レビュー/評価/sample_l数値フィルタ適用前に集計しています。</div><table class="diag-table"><thead><tr><th>API素材</th><th>総数</th><th>0P</th><th>1–4P</th><th>5–9P</th><th>10P+</th></tr></thead><tbody><?php foreach(['all','comic','cg','game','voice','other'] as $k):$s=$stats[$k];?><tr class="<?=$assetType===$k?'is-active':''?>"><td><?=h($assetTypes[$k]['label'])?></td><td><?=(int)$s['total']?></td><td><?=(int)$s['zero']?></td><td><?=(int)$s['one_to_four']?></td><td><?=(int)$s['five_to_nine']?></td><td><?=(int)$s['ten_plus']?></td></tr><?php endforeach;?></tbody></table><?php if($stats['raw_buckets']!==[]):?><div class="diag-sub" style="margin-top:8px">その他bucket: <?php $pairs=[];foreach($stats['raw_buckets'] as $k=>$v)$pairs[]=$k.':'.$v;echo h(implode(' / ',$pairs));?></div><?php endif;?></div><div class="sheet-actions"><button class="btn btn-secondary" type="button" id="resetFilters">初期値に戻す</button><button class="btn btn-primary" type="submit">この条件で見る</button></div></form>
<form class="cid-test" method="get"><input name="cid" placeholder="CID / FANZA商品URLで直接テスト" autocomplete="off"><input type="hidden" name="asset_type" value="<?=h($assetType)?>"><input type="hidden" name="genre_id" value="<?=h($genreId)?>"><input type="hidden" name="min_samples" value="<?=$minSamples?>"><input type="hidden" name="min_reviews" value="<?=$minReviews?>"><input type="hidden" name="min_rating" value="<?=h(number_format($minRating,1,'.',''))?>"><button type="submit">開く</button></form></aside><div class="toast" id="toast"></div><script src="assets/app.js"></script></body></html>
